# ── Event-images S3 bucket ───────────────────────────────────
# Stores event banner images uploaded by the admin portal via
# presigned PUT URLs generated by event-registration-api.
#
# Upload flow (why each block below exists):
#   1. Backend signs a PUT for events/<uuid>/<file> pinning
#      Content-Type + Cache-Control            -> IAM: worker role needs
#                                                 s3:PutObject/GetObject
#   2. The ADMIN'S BROWSER performs the PUT     -> CORS rule
#   3. Both portals render the image publicly   -> public-read policy
#                                                 on events/* only
#
# Wire the app (event-api-deployment.yaml) with:
#   AWS_S3_BUCKET  = <bucket output>
#   AWS_REGION     = var.aws_region
#   (no AWS_S3_ACCESS_KEY/SECRET_KEY — the worker instance role is
#   picked up by the AWS SDK default provider chain via IMDSv2;
#   compute.tf sets http_put_response_hop_limit = 2 so pods reach it)

data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "event_images" {
  # Account ID suffix keeps the name globally unique and deterministic.
  bucket = "eventslk-event-images-${data.aws_caller_identity.current.account_id}"

  tags = { Name = "eventslk-event-images" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "event_images" {
  bucket = aws_s3_bucket.event_images.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Objects are keyed events/<uuid>/<name> and never rewritten, so
# failed/abandoned multipart uploads are the only garbage to collect.
resource "aws_s3_bucket_lifecycle_configuration" "event_images" {
  bucket = aws_s3_bucket.event_images.id

  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 3
    }
  }
}

# The browser PUTs directly to S3 with the presigned URL, so the
# bucket must answer that origin's CORS preflight. Content-Type and
# Cache-Control are part of the presigned signature and MUST be listed.
resource "aws_s3_bucket_cors_configuration" "event_images" {
  bucket = aws_s3_bucket.event_images.id

  cors_rule {
    allowed_methods = ["PUT"]
    allowed_origins = var.image_upload_cors_origins
    allowed_headers = ["Content-Type", "Cache-Control"]
    max_age_seconds = 3000
  }
}

# Public READ is limited to events/* by the bucket policy below, so the
# public-access block must permit bucket policies while still blocking
# ACL-based exposure.
resource "aws_s3_bucket_public_access_block" "event_images" {
  bucket = aws_s3_bucket.event_images.id

  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = false
  restrict_public_buckets = false
}

data "aws_iam_policy_document" "event_images_public_read" {
  statement {
    sid       = "PublicReadEventImages"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.event_images.arn}/events/*"]

    principals {
      type        = "*"
      identifiers = ["*"]
    }
  }
}

resource "aws_s3_bucket_policy" "event_images" {
  bucket = aws_s3_bucket.event_images.id
  policy = data.aws_iam_policy_document.event_images_public_read.json

  depends_on = [aws_s3_bucket_public_access_block.event_images]
}

# ── Worker-node IAM role (S3 upload signing) ─────────────────
# The backend pods run on the workers and use the node's instance
# role through the SDK default chain — no static keys anywhere.

data "aws_iam_policy_document" "ec2_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "worker" {
  name               = "eventslk-worker"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume.json
  tags               = { Name = "eventslk-worker" }
}

data "aws_iam_policy_document" "event_images_rw" {
  statement {
    sid    = "EventImagesReadWrite"
    effect = "Allow"
    actions = [
      "s3:PutObject",
      "s3:GetObject",
    ]
    resources = ["${aws_s3_bucket.event_images.arn}/events/*"]
  }
}

resource "aws_iam_role_policy" "worker_event_images" {
  name   = "eventslk-event-images-rw"
  role   = aws_iam_role.worker.id
  policy = data.aws_iam_policy_document.event_images_rw.json
}

resource "aws_iam_instance_profile" "worker" {
  name = "eventslk-worker"
  role = aws_iam_role.worker.name
}
