---
- name: Join Worker Node
  hosts: worker
  become: yes
  tasks:
    - name: Copy join command to worker
      copy:
        src: ./join-command.sh
        dest: /tmp/join-command.sh
        mode: '0700'

    - name: Run join command
      shell: sh /tmp/join-command.sh

    - name: Remove join command script
      file:
        path: /tmp/join-command.sh
        state: absent
